### ISSUE TITLE
Getting NaN for Ammo, Food around Level 25

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#1]
NaN showed up in red text around Level 25 for Ammo, then it showed up for food at level 26.
Once they appeared, they didn't go away.   Death soon followed.

**Comment by dantho** [comment]
![image](https://github.com/user-attachments/assets/e31711be-0917-4d6f-8dc4-f32378f9d676)

**Comment by rthorn** [comment]
Oh no!
I did just push some updates including bug fixes but I’ve never seen that bug before, so it’s probably still there lololol. Should be easy enough to track down though...

**Comment by dantho** [comment]
Seems to be fixed.  Closing.
