### ISSUE TITLE
Javert cannot move

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#2]
Immediately after identification, I cannot move Javert to the dismiss box.  I cannot select and move him anywhere.  (I can reset him with the little "refresh" icon next to his head, but that moves him behind the barricade, then I still cannot move him from his new location.)  On the next turn, I can move him.

Not sure if this happens every time, but it has happened multiple times -- maybe every time.

**Comment by rthorn** [comment]
Can't repro this one so far either

**Comment by dantho** [comment]
This has not recurred.  Closing.
