### ISSUE TITLE
Bug: Press/Hold down shift key when moving a stack causes stack count to ramp up without end

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#4]
This is a somewhat harmless bug, since the stack count reverts to normal as soon as you let go of the shift key or the mouse.  It is FUN to watch the numbers zoom up.  I thought I would end up with 1000 citizens!  Nope.

**Comment by dantho** [comment]
https://github.com/user-attachments/assets/ef7b6a43-e00d-4b8f-946a-72e629e81175

**Comment by rthorn** [comment]
Hm, I can't reproduce this one.

**Comment by rthorn** [comment]
Reproducible on chrome. Guess I gotta download chrome.

**Comment by rthorn** [comment]
Doesn't happen on Mac chrome so only reproducible on windows chrome...

**Comment by dantho** [comment]
Still happening for me using Firefox and Edge

**Comment by rthorn** [comment]
ok maybe just Windows in general, regardless of browser

**Comment by rthorn** [comment]
no error in the console of the browser?

**Comment by rthorn** [comment]
Fixed. (windows triggers keydown for shift the entire time it is held instead of just at the start)
