### ISSUE TITLE
Bug: Cannot recruit 20th citizen

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#5]
I recruited all 20 "citizens" then discovered Javert in the mix!
While I held onto Javert, isolating him, I went to see if I could recruit one more citizen...
Nope.  Still said 20 recruited.  This is OK.  Javert was still taking up a slot.  OK.  Discard Javert!

After Javert was gone, my citizen count went down to 19 as expected.  But I cannot recruit the 20th.
Even with plenty of Hope to spend, the recruit button is greyed out.  👎 

![image](https://github.com/user-attachments/assets/92319f52-d56f-4183-8a87-6fc93bb48746)

**Comment by rthorn** [comment]
Fixed.
