### ISSUE TITLE
Shift-move of stack is PERMANENTLY sticky

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#7]
With Firefox browser, I press Shift to move a stack and I don't have to hold Shift.  In fact, the stack is frozen together as a stack and cannot be separated from each other regardless of keystroke.  The only way I've separated the stack is to Autofill them apart.  Or move the stack to a location that only needs 1 or two amis.

**Comment by rthorn** [comment]
I just fixed this today.

**Comment by dantho** [comment]
Confirmed.  Fix pushed 45 minutes ago.  Closes #4
