### ISSUE TITLE
Barricades grow to top of screen after game-over

### ISSUE THREAD

**Issue by dantho** [rthorn/The-Barricade#9]
The barricade on the left went to zero, then they all grew to the top of the screen.  The zoom up took about 2 seconds and had, maybe, 6 steps in the animation.
![image](https://github.com/user-attachments/assets/764aabe4-2de7-4d89-9a64-7545eadd1ced)

**Comment by dantho** [comment]
Also, the barricades on the left have always had that weird alignment issue.  I noticed at one point earlier in today's game that the Corinthe building was on top of the left barricade.  But then it reverted to the above view.

**Comment by rthorn** [comment]
Is your game up-to-date? I thought I fixed this but maybe there is a case I missed

**Comment by rthorn** [comment]
I will worry about alignment after having real art for the background/barricades

**Comment by dantho** [comment]
I always update before playing.  So yes.  Up to date.
**09dc5b4 (HEAD -> main, origin/main, origin/HEAD) Fix to small fixes**

And it just happened again.

**Comment by rthorn** [comment]
I hopefully just fixed this?
